FROM fedora:22

RUN dnf -y install python-pip python-mock && \
    dnf -y clean all

RUN mkdir /run/lock
ENV PYTHONPATH $PYTHONPATH:/opt/$PROJECT$/$PROJECT$

ADD . /opt/$PROJECT$

WORKDIR /opt/$PROJECT$

RUN pip install -r requirements.txt --use-mirrors && \
    pip install pytest-cov coveralls --use-mirrors && \
    pip install pep8 --use-mirrors && \
    pip install flake8 --use-mirrors

CMD python -m pytest -vv tests --cov $PROJECT$

